name: CI/CD
permissions:
  contents: read

on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '.github/workflows/*.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.cjs'
      - '!data/**'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '.github/workflows/*.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.cjs'
      - '!data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
