name: Fetch and Commit Educational Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download CSV files
        id: download-csv
        run: |
          # Create data directory if it doesn't exist
          mkdir -p data
          
          # Run the data fetcher using the npm script
          npm run download

      - name: Commit changes if any
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Check if there are changes to commit
          if [[ $(git status --porcelain) ]]; then
            # Add changes, commit and push
            git add data/
            git commit -m "Update education data files ($(date +'%Y-%m-%d'))"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
